***REMOVED***.

***REMOVED*** Licensed under the Apache License, Version 2.0 (the "License");
***REMOVED*** you may not use this file except in compliance with the License.
***REMOVED*** You may obtain a copy of the License at
***REMOVED*** http:***REMOVED***www.apache.org/licenses/LICENSE-2.0

***REMOVED*** Unless required by applicable law or agreed to in writing, software
***REMOVED*** distributed under the License is distributed on an "AS IS" BASIS,
***REMOVED*** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
***REMOVED*** See the License for the specific language governing permissions and
***REMOVED*** limitations under the License.

***REMOVED***
***REMOVED***

***REMOVED***/ Manages the state for a `BasemapGallery`.
@MainActor
public class BasemapGalleryViewModel: ObservableObject {
***REMOVED******REMOVED***/ Creates a `BasemapGalleryViewModel`
***REMOVED******REMOVED***/ - Remark: The ArcGISOnline's developer basemaps will
***REMOVED******REMOVED***/ be loaded and added to `basemapGalleryItems`.
***REMOVED******REMOVED***/ - Parameters:
***REMOVED******REMOVED***/   - geoModel: The `GeoModel`.
***REMOVED***public convenience init(_ geoModel: GeoModel? = nil) {
***REMOVED******REMOVED***self.init(geoModel, basemapGalleryItems: [])
***REMOVED***

***REMOVED******REMOVED***/ Creates a `BasemapGalleryViewModel`. Uses the given list of basemap gallery items.
***REMOVED******REMOVED***/ - Remark: If `basemapGalleryItems` is empty, ArcGISOnline's developer basemaps will
***REMOVED******REMOVED***/ be loaded and added to `basemapGalleryItems`.
***REMOVED******REMOVED***/ - Parameters:
***REMOVED******REMOVED***/   - geoModel: The `GeoModel`.
***REMOVED******REMOVED***/   - basemapGalleryItems: A list of pre-defined base maps to display.
***REMOVED***public init(
***REMOVED******REMOVED***_ geoModel: GeoModel? = nil,
***REMOVED******REMOVED***basemapGalleryItems: [BasemapGalleryItem]
***REMOVED***) {
***REMOVED******REMOVED***self.basemapGalleryItems.append(contentsOf: basemapGalleryItems)
***REMOVED******REMOVED***
***REMOVED******REMOVED***if basemapGalleryItems.isEmpty {
***REMOVED******REMOVED******REMOVED******REMOVED*** We have no basemap items, so fetch the
***REMOVED******REMOVED******REMOVED******REMOVED***developer basemaps from AGOL.
***REMOVED******REMOVED******REMOVED***fetchBasemapsTask = Task {
***REMOVED******REMOVED******REMOVED******REMOVED***await fetchBasemaps(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***from: Portal.arcGISOnline(isLoginRequired: false),
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***useDeveloperBasemaps: true
***REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED***
***REMOVED***
***REMOVED******REMOVED***
***REMOVED******REMOVED***defer {
***REMOVED******REMOVED******REMOVED******REMOVED*** Using `defer` allows the property `didSet` observers to be called.
***REMOVED******REMOVED******REMOVED***self.geoModel = geoModel
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ Creates a `BasemapGalleryViewModel`. Uses the given `Portal` to retrieve basemaps.
***REMOVED******REMOVED***/ - Parameters:
***REMOVED******REMOVED***/   - geoModel: The `GeoModel`.
***REMOVED******REMOVED***/   - portal: The `Portal` used to load basemaps.
***REMOVED***public init(
***REMOVED******REMOVED***_ geoModel: GeoModel? = nil,
***REMOVED******REMOVED***portal: Portal
***REMOVED***) {
***REMOVED******REMOVED***defer {
***REMOVED******REMOVED******REMOVED******REMOVED*** Using `defer` allows the property `didSet` observers to be called.
***REMOVED******REMOVED******REMOVED***self.geoModel = geoModel
***REMOVED******REMOVED******REMOVED***self.portal = portal
***REMOVED***
***REMOVED***

***REMOVED***private var fetchBasemapsTask: Task<Void, Never>? {
***REMOVED******REMOVED***willSet {
***REMOVED******REMOVED******REMOVED***fetchBasemapsTask?.cancel()
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ The error generated by fetching the `Basemaps` from the `Portal`.
***REMOVED***@Published
***REMOVED***public var fetchBasemapsError: Error? = nil
***REMOVED***
***REMOVED******REMOVED***/ If the `GeoModel` is not loaded when passed to the `BasemapGalleryViewModel`, then
***REMOVED******REMOVED***/ the geoModel will be immediately loaded. The spatial reference of geoModel dictates which
***REMOVED******REMOVED***/ basemaps from the gallery are enabled. When an enabled basemap is selected by the user,
***REMOVED******REMOVED***/ the geoModel will have its basemap replaced with the selected basemap.
***REMOVED***public var geoModel: GeoModel? {
***REMOVED******REMOVED***didSet {
***REMOVED******REMOVED******REMOVED***guard let geoModel = geoModel else { return ***REMOVED***
***REMOVED******REMOVED******REMOVED***Task { await load(geoModel: geoModel) ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ The `Portal` object, if any. Setting the portal will automatically fetch it's basemaps
***REMOVED******REMOVED***/ and replace the`basemapGalleryItems` array items with the fetched basemaps.
***REMOVED***public var portal: Portal? {
***REMOVED******REMOVED***didSet {
***REMOVED******REMOVED******REMOVED******REMOVED*** Remove all items from `basemapGalleryItems`.
***REMOVED******REMOVED******REMOVED***basemapGalleryItems.removeAll()

***REMOVED******REMOVED******REMOVED***guard let portal = portal else { return ***REMOVED***
***REMOVED******REMOVED******REMOVED***fetchBasemapsTask = Task { await fetchBasemaps(from: portal) ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ The list of basemaps currently visible in the gallery. It is comprised of items passed into
***REMOVED******REMOVED***/ the `BasemapGalleryItem` constructor property and items loaded either from `portal` or
***REMOVED******REMOVED***/ from ArcGISOnline if `portal` is `nil`.
***REMOVED***@Published
***REMOVED***public var basemapGalleryItems: [BasemapGalleryItem] = []
***REMOVED***
***REMOVED******REMOVED***/ The `BasemapGalleryItem` representing the `GeoModel`'s current base map. This may be a
***REMOVED******REMOVED***/ basemap which does not exist in the gallery.
***REMOVED***@Published
***REMOVED***public private(set) var currentBasemapGalleryItem: BasemapGalleryItem? = nil {
***REMOVED******REMOVED***didSet {
***REMOVED******REMOVED******REMOVED***guard let item = currentBasemapGalleryItem else { return ***REMOVED***
***REMOVED******REMOVED******REMOVED***geoModel?.basemap = item.basemap
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ The error signifying the spatial reference of the GeoModel and that of a potential
***REMOVED******REMOVED***/ current `BasemapGalleryItem` do not match.
***REMOVED***@Published
***REMOVED***public private(set) var spatialReferenceMismatchError: SpatialReferenceMismatchError? = nil
***REMOVED***
***REMOVED******REMOVED***/ This attempts to set `currentBasemapGalleryItem`. `currentBasemapGalleryItem`
***REMOVED******REMOVED***/ will be set if it's spatial reference matches that of the current geoModel. If the spatial references
***REMOVED******REMOVED***/ do not match, `currentBasemapGalleryItem` will be unchanged.
***REMOVED******REMOVED***/ - Parameter basemapGalleryItem: The new, potential, `BasemapGalleryItem`.
***REMOVED***public func updateCurrentBasemapGalleryItem(
***REMOVED******REMOVED***_ basemapGalleryItem: BasemapGalleryItem
***REMOVED***) {
***REMOVED******REMOVED***Task {
***REMOVED******REMOVED******REMOVED******REMOVED*** Ensure the geoModel is loaded.
***REMOVED******REMOVED******REMOVED***try await geoModel?.load()
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED*** Reset the mismatch error.
***REMOVED******REMOVED******REMOVED***spatialReferenceMismatchError = nil
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED*** Update the basemap gallery item's `spatialReferenceStatus`.
***REMOVED******REMOVED******REMOVED***try await basemapGalleryItem.updateSpatialReferenceStatus(
***REMOVED******REMOVED******REMOVED******REMOVED***geoModel?.actualSpatialReference
***REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED*** Update @State on the main thread.
***REMOVED******REMOVED******REMOVED***await MainActor.run {
***REMOVED******REMOVED******REMOVED******REMOVED***switch basemapGalleryItem.spatialReferenceStatus {
***REMOVED******REMOVED******REMOVED******REMOVED***case .match, .unknown:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***currentBasemapGalleryItem = basemapGalleryItem
***REMOVED******REMOVED******REMOVED******REMOVED***case .noMatch:
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***spatialReferenceMismatchError = SpatialReferenceMismatchError(
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***basemapSR: basemapGalleryItem.spatialReference,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***geoModelSR: geoModel?.actualSpatialReference
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***)
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

internal extension GeoModel {
***REMOVED******REMOVED***/ The actual spatial reference of the geoModel. For `Map`s, this is the map's
***REMOVED******REMOVED***/ `spatialReference`. For `Scene`s, if the `sceneViewTilingScheme` is
***REMOVED******REMOVED***/ `.webMercator`, the `actualSpatialReference` is `.webMercator`, otherwise
***REMOVED******REMOVED***/ it is the `spatialReference` of the scene.
***REMOVED***var actualSpatialReference: SpatialReference? {
***REMOVED******REMOVED***(self as? ArcGIS.Scene)?.sceneViewTilingScheme == .webMercator ?
***REMOVED******REMOVED***SpatialReference.webMercator :
***REMOVED******REMOVED***spatialReference
***REMOVED***
***REMOVED***

private extension BasemapGalleryViewModel {
***REMOVED******REMOVED***/ Fetches the basemaps from the given portal and appends `basemapGalleryItems` with
***REMOVED******REMOVED***/ items created from the fetched basemaps.
***REMOVED******REMOVED***/ - Parameters:
***REMOVED******REMOVED***/   - portal: Portal to fetch basemaps from
***REMOVED******REMOVED***/   - useDeveloperBasemaps: If `true`, will always use the portal's developer basemaps. If
***REMOVED******REMOVED***/   `false`, it will use either the portal's basemaps or vector basemaps, depending on the value of
***REMOVED******REMOVED***/   `portal.portalInfo.useVectorBasemaps`.
***REMOVED***func fetchBasemaps(
***REMOVED******REMOVED***from portal: Portal?,
***REMOVED******REMOVED***useDeveloperBasemaps: Bool = false
***REMOVED***) async {
***REMOVED******REMOVED***guard let portal = portal else { return ***REMOVED***
***REMOVED******REMOVED***
***REMOVED******REMOVED***do {
***REMOVED******REMOVED******REMOVED***try await portal.load()
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED***if useDeveloperBasemaps {
***REMOVED******REMOVED******REMOVED******REMOVED***basemapGalleryItems += try await portal.developerBasemaps.map {
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***BasemapGalleryItem(basemap: $0)
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED*** else if let portalInfo = portal.portalInfo,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***  portalInfo.useVectorBasemaps {
***REMOVED******REMOVED******REMOVED******REMOVED***basemapGalleryItems += try await portal.vectorBasemaps.map {
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***BasemapGalleryItem(basemap: $0)
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED*** else {
***REMOVED******REMOVED******REMOVED******REMOVED***basemapGalleryItems += try await portal.basemaps.map {
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***BasemapGalleryItem(basemap: $0)
***REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED***
***REMOVED*** catch {
***REMOVED******REMOVED******REMOVED***fetchBasemapsError = error
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED******REMOVED***/ Loads the given `GeoModel` then sets `currentBasemapGalleryItem` to an item
***REMOVED******REMOVED***/ created with the geoModel's basemap.
***REMOVED******REMOVED***/ - Parameter geoModel: The `GeoModel` to load.
***REMOVED***func load(geoModel: GeoModel?) async {
***REMOVED******REMOVED***guard let geoModel = geoModel else { return ***REMOVED***
***REMOVED******REMOVED***do {
***REMOVED******REMOVED******REMOVED***try await geoModel.load()
***REMOVED******REMOVED******REMOVED***if let basemap = geoModel.basemap {
***REMOVED******REMOVED******REMOVED******REMOVED***currentBasemapGalleryItem = BasemapGalleryItem(basemap: basemap)
***REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED***else {
***REMOVED******REMOVED******REMOVED******REMOVED***currentBasemapGalleryItem = nil
***REMOVED******REMOVED***
***REMOVED*** catch { ***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***/ A value that represents an error ocurring because of a SpatialReference mismatch between
***REMOVED***/ a geomodel and a basemap.
public struct SpatialReferenceMismatchError: Error {
***REMOVED******REMOVED***/ The basemap's spatial reference
***REMOVED***public let basemapSR: SpatialReference?
***REMOVED***
***REMOVED******REMOVED***/ The geomodel's spatial reference
***REMOVED***public let geoModelSR: SpatialReference?
***REMOVED***

extension SpatialReferenceMismatchError: Equatable {***REMOVED***
