#!/bin/sh
# Copyright 2025 Esri
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

srcroot="$(dirname "$0")/.."

ENGLISH_RESOURCES="Sources/ArcGISToolkit/Resources/en.lproj"
ENGLISH_RESOURCES_FQN="${srcroot}/${ENGLISH_RESOURCES}"
TMP_PATH="/tmp/toolkit-translations"

echo "Removing the current English strings file to allow new changes to be picked up successfully."
rm -f "${ENGLISH_RESOURCES_FQN}/Localizable.strings"
echo "Determining which SDK to use. Getting latest available iphoneos."
SDK=$(xcodebuild -showsdks | grep iphoneos | awk '{print $NF}' | sort -V | tail -1)
echo "Generating new strings."
xcodebuild -exportLocalizations -sdk "$SDK" -localizationPath "$TMP_PATH"
echo "Moving the new strings into place."
mv "${TMP_PATH}/en.xcloc/Source Contents/${ENGLISH_RESOURCES}/Localizable.strings" "${ENGLISH_RESOURCES_FQN}/"
echo "Cleaning up."
rm -rf "${TMP_PATH}"
