// Copyright 2022 Esri.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import ArcGIS
import UIKit

/// A starting point of a utility network trace.
struct UtilityNetworkTraceStartingPoint {
    /// The starting point's geometry.
    var extent: Envelope
    
    /// The underlying geo element.
    var geoElement: GeoElement
    
    /// The generated marker graphic.
    var graphic: Graphic
    
    /// The symbol of the starting point as shown on the map.
    var image: UIImage
    
    /// The underlying utility element as generated by the utility network.
    var utilityElement: UtilityElement
}

extension UtilityNetworkTraceStartingPoint: Hashable {
    static func == (lhs: UtilityNetworkTraceStartingPoint, rhs: UtilityNetworkTraceStartingPoint) -> Bool {
        lhs.utilityElement.globalID == rhs.utilityElement.globalID
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(utilityElement.globalID)
    }
}
