***REMOVED*** Copyright 2022 Esri.

***REMOVED*** Licensed under the Apache License, Version 2.0 (the "License");
***REMOVED*** you may not use this file except in compliance with the License.
***REMOVED*** You may obtain a copy of the License at
***REMOVED*** http:***REMOVED***www.apache.org/licenses/LICENSE-2.0

***REMOVED*** Unless required by applicable law or agreed to in writing, software
***REMOVED*** distributed under the License is distributed on an "AS IS" BASIS,
***REMOVED*** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
***REMOVED*** See the License for the specific language governing permissions and
***REMOVED*** limitations under the License.

***REMOVED***
import UIKit

***REMOVED***/ A starting point of a utility network trace.
struct UtilityNetworkTraceStartingPoint {
***REMOVED******REMOVED***/ The starting point's geometry.
***REMOVED***var extent: Envelope
***REMOVED***
***REMOVED******REMOVED***/ The underlying geo element.
***REMOVED***var geoElement: GeoElement
***REMOVED***
***REMOVED******REMOVED***/ The generated marker graphic.
***REMOVED***var graphic: Graphic
***REMOVED***
***REMOVED******REMOVED***/ The symbol of the starting point as shown on the map.
***REMOVED***var image: UIImage
***REMOVED***
***REMOVED******REMOVED***/ The underlying utility element as generated by the utility network.
***REMOVED***var utilityElement: UtilityElement
***REMOVED***

extension UtilityNetworkTraceStartingPoint: Hashable {
***REMOVED***static func == (lhs: UtilityNetworkTraceStartingPoint, rhs: UtilityNetworkTraceStartingPoint) -> Bool {
***REMOVED******REMOVED***lhs.utilityElement.globalID == rhs.utilityElement.globalID
***REMOVED***
***REMOVED***
***REMOVED***func hash(into hasher: inout Hasher) {
***REMOVED******REMOVED***hasher.combine(utilityElement.globalID)
***REMOVED***
***REMOVED***
